title: Caleb Torres # your name (or website title) here
logo: "/images/pro_pic.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  ...... 
  <br>Thank you for showing interest in my work. 
  This page is for showcasing my work in a range of disciplines such as data analysis, mathematics and philosophy, as well as other fields I find interesting. 
  Some of these projects have been the result of collaboration, while others reflect academic coursework, and even others stem from side projects I complete with any free time I have. <br>
  ...... 
  <br>I am recent graduate in mathematics, philosophy and computer science. 
  I enjoy learning about the intersection between mathematical fields such as topology and geometry and their applications in data analysis. 
  I also enjoy investigating philosphical questions in metaphysics, AI and language. 
  Feel free to contact me at torrescaleb385@gmail.com.<br>
  <a href="www.linkedin.com/in/caleb-torres">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
